export const data = [
  { query: 'body', tag: 'header', class: `header`, content: '' },
  { query: 'body', tag: 'main', class: `main flex-col rel`, content: '' },
  { query: 'body', tag: 'footer', class: `footer`, content: '' },
  { name: 'image', query: 'header', tag: 'img', class: `logo`, src: './src/images/logo.svg', alt: `crowdfounding logo image` },
  { name: 'image', query: 'header', tag: 'img', class: `bars mobile right selectable`, src: './src/images/icon-hamburger.svg', alt: `bars icon image` },
  { query: 'header', tag: 'nav', class: `nav desktop right`, content: `<ul class='flex-row selectable'><li>About</li><li>Discover</li><li>Get Started</li></ul>`},
  { name: 'image', query: 'main', tag: 'img', class: `mastercraft abs center`, src: './src/images/logo-mastercraft.svg', alt: `mastercraft logo image` },
  { query: 'main', tag: 'section', class: `card-1`, content: '' },
  { query: 'card-1', tag: 'h1', class: ``, content: `Mastercraft Bamboo Monitor Riser` },
  { query: 'card-1', tag: 'p', class: ``, content: `A beautiful & handcrafted monitor stand to reduce neck and eye strain.` },
  { query: 'card-1', tag: 'button', class: `button primary selectable openModal`, content: `Back this project` },
  { name: 'image', query: 'card-1', tag: 'img', class: `bookmark rel`, src: './src/images/icon-bookmark.svg', alt: `bookmark icon image` },
  { query: 'card-1', tag: 'button', class: `button secondary selectable desktop`, content: `Bookmark` },
  { query: 'main', tag: 'section', class: `card-2 flex-col`, content: '' },
  { query: 'card-2', tag: 'div', class: ``, content: `<strong>$89,914</strong><br><p>of $100,000 backed</p>` },
  { query: 'card-2', tag: 'hr', class: `separator`, content: `` },
  { query: 'card-2', tag: 'div', class: ``, content: `<strong>5,007</strong><br><p>total backers</p>` },
  { query: 'card-2', tag: 'hr', class: `separator`, content: `` },
  { query: 'card-2', tag: 'div', class: ``, content: `<strong>56</strong><br><p>days left</p>` },
  { query: 'card-2', tag: 'div', class: ``, content: `<label for="bar"></label><progress id="bar" value="89914" max="100000"></progress>` },
  { query: 'main', tag: 'section', class: `card-3`, content: '' },
  { query: 'card-3', tag: 'h2', class: ``, content: `About this project` },
  { query: 'card-3', tag: 'p', class: ``, content: `The Mastercraft Bamboo Monitor Riser is a sturdy and stylish platform that elevates your screen to a more comfortable viewing height. Placing your monitor at eye level has the potential to improve your posture and make you more comfortable while at work, helping you stay focused on the task at hand.` },
  { query: 'card-3', tag: 'p', class: ``, content: `Featuring artisan craftsmanship, the simplicity of design creates extra desk space below your computer to allow notepads, pens, and USB sticks to be stored under the stand.` },
  { query: 'card-3', tag: 'div', class: `subcard-1`, content: '' },
  { query: 'subcard-1', tag: 'h3', class: ``, content: `Bamboo Stand` },
  { query: 'subcard-1', tag: 'h4', class: `floating`, content: `Pledge $25 or more` },
  { query: 'subcard-1', tag: 'p', class: ``, content: `You get an ergonomic stand made of natural bamboo. You've helped us launch our promotional campaign, and you'll be added to a special Backer member list.` },
  { query: 'subcard-1', tag: 'strong', class: ``, content: `101 left <br>` },
  { query: 'subcard-1', tag: 'button', class: `button primary selectable floating openModal`, content: `Select Reward` },
  { query: 'card-3', tag: 'div', class: `subcard-2`, content: '' },
  { query: 'subcard-2', tag: 'h3', class: ``, content: `Black Edition Stand` },
  { query: 'subcard-2', tag: 'h4', class: `floating`, content: `Pledge $75 or more` },
  { query: 'subcard-2', tag: 'p', class: ``, content: `You get a Black Special Edition computer stand and a personal thank you. You'll be added to our Backer member list. Shipping is included.` },
  { query: 'subcard-2', tag: 'strong', class: ``, content: `64 left <br>` },
  { query: 'subcard-2', tag: 'button', class: `button primary selectable floating openModal`, content: `Select Reward` },
  { query: 'card-3', tag: 'div', class: `subcard-3`, content: '' },
  { query: 'subcard-3', tag: 'h3', class: ``, content: `Mahogany Special Edition` },
  { query: 'subcard-3', tag: 'h4', class: `floating`, content: `Pledge $200 or more` },
  { query: 'subcard-3', tag: 'p', class: ``, content: `You get two Special Edition Mahogany stands, a Backer T-Shirt, and a personal thank you. You'll be added to our Backer member list. Shipping is included.` },
  { query: 'subcard-3', tag: 'strong', class: ``, content: `0 left <br>` },
  { query: 'subcard-3', tag: 'button', class: `button secondary floating`, content: `Out of stock` },
  { query: 'footer', tag: 'div', class: `attribution`, content: `Challenge by <a class="anchor" href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. Coded by <a class="anchor" href="https://github.com/eserengo/" target="_blank">Federico Borzani</a>.` },
  { name: 'modal', query: 'body', tag: 'div', class: `modal`, content: [
      { name: 'image', query: 'modal', tag: 'img', class: `closeModalBtn right selectable`, src: './src/images/icon-close-modal.svg', alt: `close icon image` },
      { query: 'modal', tag: 'h1', class: ``, content: `Back this project` },
      { query: 'modal', tag: 'p', class: ``, content: `Want to support us in bringing Mastercraft Bamboo Monitor Riser out in the world?` },
      { name: 'form', query: 'modal', tag: 'form', class: `form-action`, attributes: `target="#" id="form" novalidate autocomplete="off"`, content: `` },
      { query: 'form-action', tag: 'div', class: `formcard-1 activating`, content: `` },
      { name: 'form', query: 'formcard-1', tag: 'label', class: `label`, attributes: `for="radio-1" form="form"`, content: `` },
      { name: 'form', query: 'formcard-1', tag: 'input', class: `radio selectable`, attributes: `type="radio" id="radio-1" name="pledge" value="0" form="form"`, content: `` },
      { query: 'formcard-1', tag: 'h3', class: `in`, content: `Pledge with no reward` },
      { query: 'formcard-1', tag: 'p', class: ``, content: `Choose to support us without a reward if you simply believe in our project. As a backer, you will be signed up to receive product updates via email.` },
      { query: 'formcard-1', tag: 'hr', class: `hidding hidden`, content: `` },
      { name: 'form', query: 'formcard-1', tag: 'button', class: `submitBtn button primary selectable hidding hidden`, attributes: `type="submit"`, content: `Continue`},
      { query: 'form-action', tag: 'div', class: `formcard-2 activating`, content: `` },
      { name: 'form', query: 'formcard-2', tag: 'label', class: `label`, attributes: `for="radio-2" form="form"`, content: `` },
      { name: 'form', query: 'formcard-2', tag: 'input', class: `radio selectable`, attributes: `type="radio" id="radio-2" name="pledge" value="25" form="form"`, content: `` },
      { query: 'formcard-2', tag: 'h3', class: `in`, content: `Bamboo Stand` },
      { query: 'formcard-2', tag: 'h4', class: `out`, content: `Pledge $25 or more` },
      { query: 'formcard-2', tag: 'p', class: ``, content: `You get an ergonomic stand made of natural bamboo. You've helped us launch our promotional campaign, and you'll be added to a special Backer member list.` },
      { query: 'formcard-2', tag: 'strong', class: `floating`, content: `101 left` },
      { query: 'formcard-2', tag: 'hr', class: `hidding hidden`, content: `` },
      { name: 'form', query: 'formcard-2', tag: 'label', class: `label hidding hidden`, attributes: `for="number-2" form="form"`, content: `Enter your pledge<br>` },
      { name: 'form', query: 'formcard-2', tag: 'input', class: `number selectable hidding hidden`, attributes: `type="number" id="number-2" placeholder="$ 25" form="form"`, content: `` },
      { name: 'form', query: 'formcard-2', tag: 'button', class: `submitBtn button primary selectable hidding hidden`, attributes: `type="submit"`, content: `Continue`},
      { query: 'form-action', tag: 'div', class: `formcard-3  activating`, content: `` },
      { name: 'form', query: 'formcard-3', tag: 'label', class: `label`, attributes: `for="radio-3" form="form"`, content: `` },
      { name: 'form', query: 'formcard-3', tag: 'input', class: `radio selectable`, attributes: `type="radio" id="radio-3" name="pledge" value="75" form="form"`, content: `` },
      { query: 'formcard-3', tag: 'h3', class: `in`, content: `Black Edition Stand` },
      { query: 'formcard-3', tag: 'h4', class: `out`, content: `Pledge $75 or more` },
      { query: 'formcard-3', tag: 'p', class: ``, content: `You get a Black Special Edition computer stand and a personal thank you. You'll be added to our Backer member list. Shipping is included.` },
      { query: 'formcard-3', tag: 'strong', class: `floating`, content: `64 left` },
      { query: 'formcard-3', tag: 'hr', class: `hidding hidden`, content: `` },
      { name: 'form', query: 'formcard-3', tag: 'label', class: `label hidding hidden`, attributes: `for="number-3" form="form"`, content: `Enter your pledge<br>` },
      { name: 'form', query: 'formcard-3', tag: 'input', class: `number selectable hidding hidden`, attributes: `type="number" id="number-3" placeholder="$ 75" form="form"`, content: `` },
      { name: 'form', query: 'formcard-3', tag: 'button', class: `submitBtn button primary selectable hidding hidden`, attributes: `type="submit"`, content: `Continue`},
      { query: 'form-action', tag: 'div', class: `formcard-4 activating`, content: `` },
      { name: 'form', query: 'formcard-4', tag: 'label', class: `label`, attributes: `for="radio-4" form="form"`, content: `` },
      { name: 'form', query: 'formcard-4', tag: 'input', class: `radio`, attributes: `type="radio" id="radio-4" name="pledge" value="200" form="form"`, content: `` },
      { query: 'formcard-4', tag: 'h3', class: `in`, content: `Mahogany Special Edition` },
      { query: 'formcard-4', tag: 'h4', class: `out`, content: `Pledge $200 or more` },
      { query: 'formcard-4', tag: 'p', class: ``, content: `You get two Special Edition Mahogany stands, a Backer T-Shirt, and a personal thank you. You'll be added to our Backer member list. Shipping is included.` },
      { query: 'formcard-4', tag: 'strong', class: `floating`, content: `0 left` },
      { query: 'formcard-4', tag: 'hr', class: `hidding hidden`, content: `` },
      { name: 'form', query: 'formcard-4', tag: 'label', class: `label hidding hidden`, attributes: `for="number-4" form="form"`, content: `Enter your pledge<br>` },
      { name: 'form', query: 'formcard-4', tag: 'input', class: `number selectable hidding hidden`, attributes: `type="number" id="number-4" placeholder="$ 200" form="form"`, content: `` },
      { name: 'form', query: 'formcard-4', tag: 'button', class: `submitBtn button primary selectable hidding hidden`, attributes: `type="submit"`, content: `Continue` },
      { name: 'modal-completed', query: 'body', tag: 'div', class: 'modal completed flex-col center', content: [
        { name: 'image', query: 'completed', tag: 'img', class: `check`, src: './src/images/icon-check.svg', alt: `check icon image` },
        { query: 'completed', tag: 'h1', class: ``, content: `Thanks for your support!` },
        { query: 'completed', tag: 'p', class: ``, content: `Your pledge brings us one step closer to sharing Mastercraft Bamboo Monitor Riser worldwide. You will get an email once our campaign is completed.` },
        { query: 'completed', tag: 'button', class: `closeCompletedBtn button primary selectable`, content: `Got it!` },
      ]
    },
  ]
  },
  { name: 'menu', query: 'body', tag: 'nav', class: `popup`, content: [
      { name: 'image', query: 'popup', tag: 'img', class: `closeMenuBtn selectable`, src: './src/images/icon-close-menu.svg', alt: `close icon image` },
      { query: 'popup', tag: 'ul', class: `flex-col selectable`, content: `<li>About</li><hr><li>Discover</li><hr><li>Get Started</li>` },
    ]
  },
];